#frontend
services:
  frontend:
    container_name: frontend_jsEdior
    build: ./frontend
    env_file:
      - ./frontend/frontend.env
    environment:
      - TZ=Asia/Kathmandu
    ports:
      - "5173:5173"
    command: >
      npm run start:dev
  backend:
    container_name: backend_jsEditor
    build: ./backend/
    environment:
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - database
    command: >
      npm run start:dev
    ports:
      - ${PORT}:3000
    restart: always
    volumes:
      - .:/app

  database:
    image: postgres:16.3-alpine3.19
    container_name: postgres_jsEditor
    env_file:
      - ./backend/backend.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=Asia/Kathmandu
    volumes:
      - postgres_data_discord:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data_jsEditor:
